version: "3.10-slim"

services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    environment:
      - DATABASE_URL=postgresql://${TEST_DB_USER}:${TEST_DB_PASSWORD}@${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}

  test_db:
    extends:
      file: docker-compose.yml
      service: prod_db
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
    volumes:
      - test_db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - app_network

volumes:
  test_db_data: